from pathlib import Path
import pandas as pd
import numpy as np
import sys

# =============================================================================
# PERTURBATION / WHAT-IF ML LEAKAGE AUDIT V2
# =============================================================================

BASE = Path(r"C:\Users\Ali\Desktop\BrainPerturbationProject")

OUT_DIR = (
    BASE
    / "features"
    / "perturbation_analysis"
    / "ml_leakage_audit_v2"
)

OUT_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 90)
print("PERTURBATION / WHAT-IF ML LEAKAGE AUDIT V2")
print("=" * 90)
print(f"Project root: {BASE}")

# =============================================================================
# 1. SEARCH FOR THE CORRECT ML DATASET
# =============================================================================

print("\n" + "=" * 90)
print("SEARCHING FOR DATASET WITH SUBJECT + TARGETS + EEG FEATURES")
print("=" * 90)

candidate_files = []

search_roots = [
    BASE / "features",
    BASE / "qc",
]

for root in search_roots:
    if root.exists():
        candidate_files.extend(root.rglob("*.csv"))

required_target_cols = {
    "target_remember",
    "target_correct",
}

required_subject_cols = {
    "subject",
}

best_file = None
best_score = -1

for file in candidate_files:

    # Avoid outputs generated by this audit
    if "ml_leakage_audit" in str(file).lower():
        continue

    try:
        df_tmp = pd.read_csv(file, nrows=5)
    except Exception:
        continue

    cols = set(df_tmp.columns)

    score = 0

    if "subject" in cols:
        score += 10

    if "target_remember" in cols:
        score += 10

    if "target_correct" in cols:
        score += 10

    # EEG feature candidates
    eeg_candidates = [
        "delta_abs",
        "theta_abs",
        "alpha_abs",
        "beta_abs",
        "gamma_abs",
        "delta_rel",
        "theta_rel",
        "alpha_rel",
        "beta_rel",
        "gamma_rel",
    ]

    score += sum(1 for c in eeg_candidates if c in cols)

    if score > best_score:
        best_score = score
        best_file = file


if best_file is None or best_score < 20:
    print("\nERROR: Could not find a valid ML dataset.")
    print("The required dataset must contain:")
    print("  subject")
    print("  target_remember")
    print("  target_correct")
    print("  EEG feature columns")
    sys.exit(1)


INPUT = best_file

print("\nINPUT FOUND:")
print(INPUT)

# =============================================================================
# 2. LOAD DATA
# =============================================================================

df = pd.read_csv(INPUT)

print("\n" + "=" * 90)
print("DATASET SUMMARY")
print("=" * 90)

print(f"Rows:       {len(df):,}")
print(f"Columns:    {len(df.columns)}")
print(f"Subjects:   {df['subject'].nunique()}")

print("\nColumns:")
print(list(df.columns))

# =============================================================================
# 3. TARGET VALIDATION
# =============================================================================

print("\n" + "=" * 90)
print("TARGET VALIDATION")
print("=" * 90)

for target in ["target_remember", "target_correct"]:

    if target not in df.columns:
        print(f"{target}: NOT FOUND")
        continue

    print(f"\n{target}: FOUND")

    print(df[target].value_counts(dropna=False))

    print(
        f"Unique values: "
        f"{df[target].dropna().unique()[:20]}"
    )

# =============================================================================
# 4. IDENTIFY EEG FEATURES
# =============================================================================

print("\n" + "=" * 90)
print("IDENTIFYING EEG FEATURES")
print("=" * 90)

exclude_cols = {
    "file",
    "subject",
    "run",
    "epoch",
    "trial",
    "memory_cond",
    "probe_type",
    "probe_letter",
    "target_label",
    "target_remember",
    "target_correct",
}

feature_cols = []

for col in df.columns:

    if col in exclude_cols:
        continue

    if pd.api.types.is_numeric_dtype(df[col]):
        feature_cols.append(col)

print(f"Numeric candidate features: {len(feature_cols)}")

print("\nFirst features:")
for x in feature_cols[:60]:
    print(" ", x)

# =============================================================================
# 5. CHECK FOR DIRECT TARGET LEAKAGE
# =============================================================================

print("\n" + "=" * 90)
print("DIRECT TARGET LEAKAGE CHECK")
print("=" * 90)

leakage_records = []

targets = [
    "target_remember",
    "target_correct",
]

for target in targets:

    if target not in df.columns:
        continue

    y = df[target]

    for feature in feature_cols:

        x = df[feature]

        valid = x.notna() & y.notna()

        if valid.sum() == 0:
            continue

        x_valid = x.loc[valid]
        y_valid = y.loc[valid]

        # Exact equality
        exact_equal = False

        try:
            if len(x_valid) == len(y_valid):
                exact_equal = np.array_equal(
                    x_valid.to_numpy(),
                    y_valid.to_numpy()
                )
        except Exception:
            pass

        # Correlation
        correlation = np.nan

        if x_valid.nunique() > 1 and y_valid.nunique() > 1:
            try:
                correlation = np.corrcoef(
                    x_valid.astype(float),
                    y_valid.astype(float)
                )[0, 1]
            except Exception:
                correlation = np.nan

        leakage_records.append(
            {
                "target": target,
                "feature": feature,
                "exact_equal": exact_equal,
                "correlation": correlation,
                "n_valid": int(valid.sum()),
            }
        )

leakage_df = pd.DataFrame(leakage_records)

if len(leakage_df) > 0:

    leakage_df["abs_correlation"] = leakage_df["correlation"].abs()

    suspicious = leakage_df[
        (leakage_df["exact_equal"])
        | (leakage_df["abs_correlation"] >= 0.999999)
    ].copy()

else:
    suspicious = pd.DataFrame()

print(f"Features checked: {len(leakage_df)}")
print(f"Suspicious direct leakage pairs: {len(suspicious)}")

if len(suspicious) > 0:
    print("\nWARNING - SUSPICIOUS FEATURES:")
    print(suspicious.to_string(index=False))
else:
    print("\nPASS - No direct target-copy leakage detected.")

# =============================================================================
# 6. SUBJECT LEVEL DUPLICATE / CROSS-SPLIT RISK
# =============================================================================

print("\n" + "=" * 90)
print("SUBJECT-LEVEL STRUCTURE AUDIT")
print("=" * 90)

subject_summary = (
    df.groupby("subject")
    .agg(
        rows=("subject", "size"),
        remember_values=("target_remember", "nunique"),
        correct_values=("target_correct", "nunique"),
    )
    .reset_index()
)

print(subject_summary.head(20).to_string(index=False))

multi_target_subjects = subject_summary[
    (subject_summary["remember_values"] > 1)
    | (subject_summary["correct_values"] > 1)
]

print(
    f"\nSubjects with multiple target values: "
    f"{len(multi_target_subjects)}"
)

if len(multi_target_subjects) > 0:
    print(
        "NOTE: Multiple target values per subject are expected "
        "for trial-level behavioral prediction."
    )

# =============================================================================
# 7. IDENTIFY CONSTANT / ID-LIKE FEATURES
# =============================================================================

print("\n" + "=" * 90)
print("FEATURE STRUCTURE AUDIT")
print("=" * 90)

structure_records = []

for feature in feature_cols:

    s = df[feature]

    structure_records.append(
        {
            "feature": feature,
            "n_unique": int(s.nunique(dropna=True)),
            "missing": int(s.isna().sum()),
            "mean": s.mean(),
            "std": s.std(),
            "min": s.min(),
            "max": s.max(),
        }
    )

structure_df = pd.DataFrame(structure_records)

constant_features = structure_df[
    structure_df["n_unique"] <= 1
].copy()

print(f"Constant features: {len(constant_features)}")

if len(constant_features) > 0:
    print(constant_features.to_string(index=False))

# =============================================================================
# 8. TARGET-LIKE FEATURE NAME AUDIT
# =============================================================================

print("\n" + "=" * 90)
print("TARGET-LIKE COLUMN NAME AUDIT")
print("=" * 90)

target_like_keywords = [
    "target",
    "label",
    "class",
    "correct",
    "remember",
    "response",
    "accuracy",
    "outcome",
]

target_like_columns = []

for col in df.columns:

    col_lower = col.lower()

    if any(k in col_lower for k in target_like_keywords):
        target_like_columns.append(col)

print("Potential target-related columns:")

for col in target_like_columns:
    print(" ", col)

# =============================================================================
# 9. SUBJECT-LEVEL FEATURE DUPLICATION CHECK
# =============================================================================

print("\n" + "=" * 90)
print("SUBJECT-LEVEL DUPLICATION CHECK")
print("=" * 90)

duplicate_subject_feature_risk = []

for feature in feature_cols:

    nunique_per_subject = (
        df.groupby("subject")[feature]
        .nunique(dropna=True)
    )

    # Feature completely constant within subject
    constant_subject_fraction = (
        (nunique_per_subject <= 1).mean()
    )

    duplicate_subject_feature_risk.append(
        {
            "feature": feature,
            "constant_within_subject_fraction":
                constant_subject_fraction,
        }
    )

subject_feature_df = pd.DataFrame(
    duplicate_subject_feature_risk
)

# =============================================================================
# 10. FINAL AUDIT SUMMARY
# =============================================================================

print("\n" + "=" * 90)
print("FINAL ML LEAKAGE AUDIT QC")
print("=" * 90)

print(f"Input file:               {INPUT}")
print(f"Rows:                     {len(df):,}")
print(f"Subjects:                 {df['subject'].nunique()}")
print(f"Numeric features:         {len(feature_cols)}")
print(f"Direct leakage pairs:     {len(suspicious)}")
print(f"Constant features:        {len(constant_features)}")

nan_cells = int(
    df.select_dtypes(include=[np.number]).isna().sum().sum()
)

inf_cells = int(
    np.isinf(
        df.select_dtypes(include=[np.number]).to_numpy()
    ).sum()
)

print(f"NaN numeric cells:        {nan_cells}")
print(f"Inf numeric cells:        {inf_cells}")

# =============================================================================
# 11. SAVE RESULTS
# =============================================================================

print("\n" + "=" * 90)
print("SAVING LEAKAGE AUDIT")
print("=" * 90)

leakage_path = OUT_DIR / "ml_leakage_feature_audit_v2.csv"
structure_path = OUT_DIR / "ml_feature_structure_audit_v2.csv"
subject_path = OUT_DIR / "ml_subject_structure_audit_v2.csv"
summary_path = OUT_DIR / "ml_leakage_audit_summary_v2.csv"

leakage_df.to_csv(
    leakage_path,
    index=False
)

structure_df.to_csv(
    structure_path,
    index=False
)

subject_feature_df.to_csv(
    subject_path,
    index=False
)

summary = pd.DataFrame(
    [
        {
            "input_file": str(INPUT),
            "rows": len(df),
            "subjects": df["subject"].nunique(),
            "numeric_features": len(feature_cols),
            "direct_leakage_pairs": len(suspicious),
            "constant_features": len(constant_features),
            "nan_numeric_cells": nan_cells,
            "inf_numeric_cells": inf_cells,
        }
    ]
)

summary.to_csv(
    summary_path,
    index=False
)

print("\nSaved:")
print(leakage_path)
print(structure_path)
print(subject_path)
print(summary_path)

# =============================================================================
# 12. FINAL STATUS
# =============================================================================

print("\n" + "=" * 90)

if len(suspicious) == 0:
    print("STATUS: PASS - NO DIRECT TARGET LEAKAGE DETECTED")
else:
    print("STATUS: REVIEW_REQUIRED - POTENTIAL TARGET LEAKAGE DETECTED")

print("=" * 90)